projects/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

projects/config/urls.py
from django.contrib import admin
from django.urls import path, include
from question.views import base_views

urlpatterns = [
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('admin/', admin.site.urls),
    path('question/', include('question.urls')),
    path('common/', include('common.urls')),
]

projects/question/urls.py
from django.urls import path

from .views import base_views, question_views

app_name = 'question'

urlpatterns = [
    path('', base_views.index, name='index'),
    
    path('create/',
         question_views.createQuestion, name='question_create'),
    path('delete/<int:question_id>/',
         question_views.deleteQuestion, name='question_delete'),
    path('vote/<int:question_id>/',
         question_views.voteQuestion, name='question_vote'),
]

projects/common/models.py
from django.db import models

# Create your models here.

projects/question/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question', null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question', null=True)

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer', null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer', null=True)

projects/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

projects/question/forms.py
from django import forms
from question.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        
        labels = {
            'subject': '제목',
            'content': '내용',
        }

projects/common/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from common.forms import UserForm

def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

projects/question/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.db.models import Q

from ..models import Question

def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list':question_list}
    return render(request, 'question/profile.html', context)

projects/question/views/modal_view.py
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from question.forms import QuestionForm
from django.views.decorators.csrf import csrf_exempt

from ..models import Question

@csrf_exempt
@login_required(login_url='common:login')
def createQuestion(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('question:index')
    else:
        form = QuestionForm()
    return render(request, 'question.html', {'form': form})

projects/question/views/question_views.py
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,get_object_or_404
from question.forms import QuestionForm
from django.views.decorators.csrf import csrf_exempt

from ..models import Question

@csrf_exempt
@login_required(login_url='common:login')
def createQuestion(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('question:index')
    else:
        form = QuestionForm()
    return render(request, 'question.html', {'form': form})

@login_required(login_url='common:login')
def deleteQuestion(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('question:index')
    messages.success(request, '삭제되었습니다.')
    # question.delete()
    return redirect('question:index')

@login_required(login_url='common:login')
def voteQuestion(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    messages.success(request, '추천되었습니다.')
    return redirect('question:index')

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <script
      src="https://kit.fontawesome.com/3a115195d8.js"
      crossorigin="anonymous"
    ></script>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap.min.css' %}"
    />
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

    <title>무엇이든지 물어보세요!</title>
  </head>
  <body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %} {% include "messages.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="/static/js/profile.js"></script>
    <script type="text/javascript" src="/static/js/message.js"></script>
    <!-- 자바스크립트 Start -->
    <!-- 자바스크립트 End -->
  </body>
</html>

projects/templates/common/login.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <form method="post" action="{% url 'common:login' %}">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="username">사용자ID</label>
      <input
        type="text"
        class="form-control"
        name="username"
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password">비밀번호</label>
      <input
        type="password"
        class="form-control"
        name="password"
        id="password"
        value="{{ form.password.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary">로그인</button>
  </form>
</div>
{% endblock %}

projects/templates/common/signup.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <form method="post" action="{% url 'common:signup' %}">
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="username">사용자 이름</label>
      <input
        type="text"
        class="form-control"
        name="username"
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password1">비밀번호</label>
      <input
        type="password"
        class="form-control"
        name="password1"
        id="password1"
        value="{{ form.password1.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="password2">비밀번호 확인</label>
      <input
        type="password"
        class="form-control"
        name="password2"
        id="password2"
        value="{{ form.password2.value|default_if_none:'' }}"
      />
    </div>
    <div class="mb-3">
      <label for="email">이메일</label>
      <input
        type="text"
        class="form-control"
        name="email"
        id="email"
        value="{{ form.email.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary">생성하기</button>
  </form>
</div>
{% endblock %}

projects/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
  <!-- 필드 오류 -->
  {% if field.errors %}
  <div>
    <strong>{{ field.label }}</strong>
    {{ field.errors }}
  </div>
  {% endif %} {% endfor %}
  <!-- 넌필드 오류 -->
  {% for error in form.non_field_errors %}
  <div>
    <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}

projects/templates/messages.html
{% for message in messages %}
<div
  class="alert message {{ message.tags }} alert-auto-dismissible notification-container text-center"
  role="alert"
>
  {{ message }}
</div>
{% endfor %}

projects/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid flex">
    <div class="Uheeking">Uheeking</div>
    <div style="display: flex">
      {% if not user.is_authenticated %}
      <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
      <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
      {% else %}
      <a class="nav-link" href="{% url 'common:logout' %}"
        >{{ user.username }} (로그아웃)</a
      >
      {% endif %}
    </div>
  </div>
</nav>

projects/templates/question/profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div id="myModal" class="modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="padding: 10px">
      <span
        class="close"
        onmouseover="this.style.cursor='pointer'"
        onmouseout="this.style.cursor='';"
        >&times;</span
      >
      <h5 class="my-3 border-bottom pb-2">질문등록</h5>
      <form action="{% url 'question:question_create' %}" method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %} {% if field.errors %}
          <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
          </div>
          {% endif %} {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
          <label for="subject" class="form-label">제목</label>
          <input
            type="text"
            class="form-control"
            name="subject"
            id="subject"
            value="{{ form.subject.value|default_if_none:'' }}"
          />
        </div>
        <div class="mb-3">
          <label for="content" class="form-label">내용</label>
          <textarea class="form-control" name="content" id="content" rows="10">
{{ form.content.value|default_if_none:'' }}</textarea
          >
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
      </form>
    </div>
  </div>
</div>
<div style="display: flex flex-direction:column">
  <div>
    <div class="container my-3 profile_div">
      <img src="{% static 'image/profile.png' %}" class="profile" />
      <div class="profile_div">
        <div class="nameis">My name is</div>
        <div class="span_uheeking">Uheeking</div>
      </div>
    </div>
    <div class="icons">
      <button class="question" id="modalButton">
        질문하기
        <i class="fa-solid fa-arrow-pointer"></i>
      </button>
    </div>
  </div>
  {% if question_list %} {% for question in question_list %}
  <div style="padding-top: 30px">
    <div
      class="max-w-2xl mx-auto rounded-lg bg-dark p-4 text-white"
      style="border-radius: 4%; margin: 0 auto; width: 300px"
    >
      <div class="flex items-center justify-between pb-2">
        <div class="flex_balance">
          <div class="color_flex">
            <div class="circle bg-red"></div>
            <div class="circle bg-yellow"></div>
            <div class="circle bg-green"></div>
            <div class="circle bg-blue"></div>
            {% if question.voter.exists %} {% for user in question.voter.all %}
            {% if request.user == user %}
            <i class="fa-solid fa-heart"></i>
            {% else %}
            <a
              href="{% url 'question:question_vote' question.id %}"
              onclick="return confirm('해당글을 추천하시겠습니까?')"
              class="recommend btn btn-sm btn-outline-secondary heart"
            >
              <i class="fa-regular fa-heart"></i>
            </a>
            {% endif %} {% endfor %} {% endif %}
          </div>
          <div class="text-xs text-gray-400">bash</div>
        </div>
      </div>
      <div class="text-green-400">
        <p class="text-green">$ {{ question.author }}</p>
        <p class="font-mono">
          {{ question.subject }}/{{ question.create_date }}
        </p>
        <p class="font-mono">{{ question.content }}</p>
        {% if request.user == question.author %}
        <p class="text-green">
          $ 삭제하시겠습니까?
          <a
            href="{% url 'question:question_delete' question.id  %}"
            onclick="return confirm('정말로 삭제하시겠습니까?')"
            class="text-green delete btn btn-sm btn-outline-secondary"
            >Yes</a
          >
        </p>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %} {% endif %} {% endblock %}
</div>